config/routes.rb
Rails.application.routes.draw do
  resources :companies
  get 'home/index'

  devise_for :users
  root to: "home#index"
  get '/hr' => 'home#hr'
  get '/home/add_hr' => 'home#add_hr'
  get '/home/add_user' => 'home#add_user'
  post '/home/save_user' => 'home#save_user'
  post '/home/update_user' => 'home#update_user'
  delete '/home/delete_user' => 'home#delete_user'
  delete '/home/delete_project' => 'home#delete_project'
  get '/home/edit_user' => 'home#edit_user'
  get '/employees' => 'home#employees'
  get '/home/new_project' => 'home#new_project'
  post '/home/save_project' => 'home#save_project'
  get '/home/edit_project' => 'home#edit_project'
  post '/home/update_project' => 'home#update_project'
  get '/home/show_excel' => 'home#show_excel'
  get '/ongoing_projects' => 'home#ongoing_projects'
  get '/completed_projects' => 'home#completed_projects'
  post '/home/save_record' => 'home#save_record'
  get '/edit_record' => 'home#edit_record'
  delete '/home/delete_record' => 'home#delete_record'
  delete '/home/delete_scrap' => 'home#delete_scrap'
  get '/home/market_value' => 'home#market_value'
  post '/home/update_market_value' => 'home#update_market_value'
  post '/save_market_value' => 'home#save_market_value'
  get 'scrap_data' => 'home#scrap_data'
  post 'save_scrap_data' => 'home#save_scrap_data'
  post 'update_final_value' => 'home#update_final_value'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user!
  def index
    if current_user.role == :director || current_user.role == :manager || current_user.role == :admin 
      if current_user.role == :admin
        @q = Project.ransack(params[:q])
      elsif current_user.role == :director || current_user.role == :manager
        @q = current_user.company.projects.ransack(params[:q])
      end
      @projects = @q.result.paginate(:page => params[:page], :per_page => 10)
    else
      root_url
    end
  end
  def ongoing_projects
    if current_user.role == :director || current_user.role == :manager || current_user.role == :admin 
      if current_user.role == :admin
        @projects = Project.where("DATE(end_date) > ?", Date.today.to_s).paginate(:page => params[:page], :per_page => 10)
      else
        @projects = current_user.company.projects.where("DATE(end_date) > ?", Date.today.to_s).paginate(:page => params[:page], :per_page => 10)  
      end
    else
      redirect_to root_url
    end
  end
  def completed_projects
    if current_user.role == :director || current_user.role == :manager || current_user.role == :admin 
      if current_user.role == :admin
        @projects = Project.where("DATE(end_date) < ?", Date.today.to_s).paginate(:page => params[:page], :per_page => 10)
      else
        @projects = current_user.company.projects.where("DATE(end_date) < ?", Date.today.to_s).paginate(:page => params[:page], :per_page => 10)  
      end
    else
      redirect_to root_url
    end
  end
  def new_project
    if current_user.role == :director || current_user.role == :manager || current_user.role == :admin
      @project = Project.new
      @errors = params[:errors]
    else
      root_url
    end
  end
  def save_project
    if project_params.present?
      @project = Project.new project_params
      if @project.save
        if @project.file_file_size.present?
          if current_user.role == :admin
            AdminDb.import @project
          else
            ExcelDatum.import @project
          end
        end
        flash[:notice] = "Project successfully added! Some fields might take time.."
        redirect_to home_show_excel_path({:id => @project.id})
      else
        redirect_to home_new_project_path({:errors => @project.errors.messages})
      end
    end
  end
  def show_excel
    if params[:id].present?
      @project = Project.where(:id => params[:id]).last
      if current_user.role == :admin
        if params[:record_id].present?
          @excel = AdminDb.where(:id => params[:record_id]).last
          if @excel.blank?
            @excel = AdminDb.new
          end 
        else
          @excel = AdminDb.new
        end
        @records = @project.admin_dbs.paginate(:page => params[:page], :per_page => 10)
      else
        if params[:record_id].present?
          @excel = ExcelDatum.where(:id => params[:record_id]).last 
          if @excel.blank?
            @excel = ExcelDatum.new
          end 
        else
          @excel = ExcelDatum.new
        end
        @records = @project.excel_datum.paginate(:page => params[:page], :per_page => 10)
      end
    else
      redirect_to root_url
    end
    respond_to do |format|
      format.html
      format.xlsx {
        if current_user.role == :admin
          file_path = AdminDb.generate_excel params[:id]
        else 
          file_path = ExcelDatum.generate_excel params[:id]
        end
        if file_path.present?
          send_file file_path
        end
      }
    end
  end
  def save_record
    if params[:id].present?
      project = Project.where(:id => params[:id]).last
      if project.present?
        if excel_params.present?
          if current_user.role == :admin
            if excel_params[:id].present?
              excel = AdminDb.where(:id => excel_params[:id]).last
              excel.update_attributes(admin_db_params)
            else
              excel = AdminDb.new admin_db_params
            end
          else
            if excel_params[:id].present?
              excel = ExcelDatum.where(:id => excel_params[:id]).last
              excel.update_attributes(excel_params)
            else
              excel = ExcelDatum.new excel_params
            end
          end
          excel.project_id = params[:id]
          if excel.save
            flash[:notice] = "Successfully saved!"
          else
            flash[:notice] = "Something went wrong!"
          end
          redirect_to home_show_excel_path({:id => project.id})
        end
      else
        redirect_to root_url
      end
    else
      redirect_to root_url
    end
  end
  def delete_record
    if params[:id].present?
      if current_user.role == :admin
        record = AdminDb.where(:id => params[:id]).last
      else
        record = ExcelDatum.where(:id => params[:id]).last
      end
      if record.present? and record.destroy
        flash[:notice] = "Successfully Destroyed!"
      else
        flash[:notice] = "Something went wrong!"
      end
      redirect_to request.referer
    else
      redirect_to request.referer  
    end
  end
  def delete_scrap
    if params[:id].present?
      record = ScrapRecord.where(:id => params[:id]).last
      if record.present? and record.destroy
        flash[:notice] = "Successfully Destroyed!"
      else
        flash[:notice] = "Something went wrong!"
      end
      redirect_to request.referer
    else
      redirect_to request.referer  
    end
  end
  def edit_project
    if params[:id].present?
      @project = Project.where(:id => params[:id]).last
      if @project.blank?
        redirect_to root_url
      end
      @errors = params[:errors]
    else
      redirect_to root_url
    end
  end
  def market_value
    if params[:id].present?
      if current_user.role == :admin
        @record = AdminDb.where(:id => params[:id]).last
      else
        @record = ExcelDatum.where(:id => params[:id]).last
      end
      if params[:scrap_id].present?
        @scrap = ScrapRecord.where(:id => params[:scrap_id]).last
        if @scrap.blank?
          @scrap = ScrapRecord.new
        end
      else
        @scrap = ScrapRecord.new
      end
      if @record.present?
        @records = ScrapRecord.where("name like ?","%#{@record.com_name.gsub(/\d+/,"")}%")
      end
    else
      redirect_to root_url  
    end
  end
  def update_market_value
    if params[:record_id].present? and params[:value].present?
      if current_user.role == :admin
        record = AdminDb.where(:id => params[:record_id]).last
      else
        record = ExcelDatum.where(:id => params[:record_id]).last
      end
      if record.present?
        scrap = ScrapRecord.where(:id => params[:value]).last
        if scrap.present?
          record.update_attributes(:source => scrap.source, :market_value => scrap.price_pp)
          flash[:notice] = "Successfully Added Market Value!"
        else
          flash[:notice] = "Something went wrong!"  
        end
        redirect_to home_show_excel_path({:id => record.project.id})
      else
        redirect_to root_url
      end
    end
  end
  def update_project
    if project_params.present? and params[:id]
      @project = Project.find params[:id]
      if @project.present? && @project.update_attributes(project_params)
        flash[:notice] = "Successfully Updated!"
        redirect_to root_url
      else
        redirect_to home_edit_project_path({:errors => @project.errors.messages, :id => @project.id})
      end
    else
      redirect_to root_url  
    end
  end
  def save_market_value
    if scrap_params.present?
      if params[:scrap_id].present?
        @scrap = ScrapRecord.where(:id => params[:scrap_id]).last
        @scrap.update_attributes(scrap_params)
        flash[:notice] = "Successfully Updated!"
      else
        @scrap = ScrapRecord.new scrap_params
        @scrap.save
        flash[:notice] = "Successfully Added!"
      end
      redirect_to request.referer
    else
      redirect_to root_url
    end
  end
  def employees
  	if current_user.role == :hr || current_user.role == :director
  		@users = current_user.company.users.where('role_cd != 3 and role_cd != 4')
  	else
  		redirect_to root_url
  	end
  end
  def hr
  	@users = User.where('role_cd = 3')
  end
  def add_hr
  	@user = User.new(:role_cd => 3)
  	@errors = params[:errors]
  end
  def add_user
  	@user = User.new
  	@errors = params[:errors]
  end
  def save_user
  	if user_params.present?
  		@user =  User.new user_params
  		if params[:company].present?	
  			@user.company_id = params[:company][:name] 
  		else
  			@user.company_id = current_user.company_id	
  		end
  		if @user.save
  			flash[:notice] = "User Successfully Created!"
  			if current_user.role == :admin 
  			  redirect_to hr_path
  			else
  				redirect_to employees_path
  			end
  		else
  			if current_user.role == :admin 
  			  redirect_to home_add_hr_path({:errors => @user.errors.messages})
  			else
  				redirect_to home_add_user_path({:errors => @user.errors.messages})
  			end
  		end
  	else
  		redirect_to root_url
  	end
  end

  def delete_project
    if params[:id].present?
      project = Project.where(:id => params[:id]).last
      if project.destroy
        flash[:notice] = "Successfully Destroyed!"
        redirect_to root_url
      else
        flash[:notice] = "Something went wrong!"
        redirect_to root_url
      end
    else
      redirect_to root_url
    end
  end

  def delete_user
  	if params[:id].present?
  		user = User.where(:id => params[:id]).last
  		if user.destroy
  			flash[:notice] = "Successfully Destroyed!"
  			if current_user.role == :admin 
  			  redirect_to hr_path
  			else
  				redirect_to employees_path
  			end
  		else
  			flash[:notice] = "Something went wrong!"
  			if current_user.role == :admin 
  			  redirect_to hr_path
  			else
  				redirect_to employees_path
  			end
  		end
    else
      redirect_to root_url  
  	end
  end

  def edit_user

app/helpers/home_helper.rb
module HomeHelper
	def username(id)
		user = User.where(:id => id).last
		if user.present?
			return user.name
		else
			return ""
		end
	end
	def final_value_a(id)
		if current_user.role == :admin
			record = AdminDb.where(:id => id).last
		else
			record = ExcelDatum.where(:id => id).last
		end	
		if record.present?
			begin
				diff = (record.exp_life.to_f-(((Date.today-record.purchase_date.to_date).to_i)/365.0)).round(2)
				fvalue = ((record.purchase_unit*(record.inflation.split("%")[0].to_f))**(((Date.today-record.purchase_date.to_date).to_i)/365.0)*record.obsolete.split("%")[0].to_f*diff)/record.exp_life.to_f	
			rescue
				fvalue = 0.0
			end
		else
			fvalue = 0.0	
		end
		return fvalue.nan? ? 0.0 : fvalue.round(2)
	end
	def final_value_b(id)
		if current_user.role == :admin
			record = AdminDb.where(:id => id).last
		else
			record = ExcelDatum.where(:id => id).last
		end	
		if record.present?
			begin
				fvalue = ((record.est_price_soft*(record.inflation.split("%")[0].to_f))**(((Date.today-record.purchase_date.to_date).to_i)/365.0))*record.obsolete.split("%")[0].to_f
			rescue
				fvalue = 0.0
			end
		else
			fvalue = 0.0	
		end
		return fvalue.nan? ? 0.0 : fvalue.round(2)
	end
	def final_value_c(id)
		if current_user.role == :admin
			record = AdminDb.where(:id => id).last
		else
			record = ExcelDatum.where(:id => id).last
		end	
		if record.present?
			begin
				fvalue = ((record.est_price_pp*(record.inflation.split("%")[0].to_f))**(((Date.today-record.purchase_date.to_date).to_i)/365.0))*record.obsolete.split("%")[0].to_f
			rescue
				fvalue = 0.0
			end
		else
			fvalue = 0.0	
		end
		return final_value = fvalue.nan? ? 0.0 : fvalue.round(2)
	end
end

app/views/home/_project.html.erb
<%= render 'layouts/messages' %>
<div class="block">
  <div class="block-title">
    <h2>Add Project</h2>
  </div>
  <% if management? %>
    <%= form_for @project, :as => :project, :url => @project.id.present? ? home_update_project_path(@project) : home_save_project_path(@project), :method => :post do |f| %>
      <% if @errors.present? %>
        <div>
          <ul>
          <% @errors.each do |k,v| %>
            <li class="alert alert-danger"><%= k %> <%= v[0] %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <%= render 'layouts/messages' %>
      <div class="row">
        <div class="col-md-6">
          <div class="field">
            <%= label_tag :name %><br>
            <%= f.text_field :name, :class => "form-control", :required => "required" %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="field">
            <%= label_tag :bank_name %><br>
            <%= f.text_field :bank_name, :class => "form-control", :required => "required" %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="field">
            <%= label_tag :end_date %><br>
            <%= f.date_field :end_date, :class => "form-control", :required => "required" %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="field">
            <%= label_tag :industry_type %><br>
            <%= f.text_field :company_type, :class => "form-control", :required => "required" %>
          </div>
        </div>
      </div>
      <div class="row">
      <% if current_user.role == :admin %>
        <div class="col-md-6">
          <div class="field">
            <%= label_tag :industry_name %><br>
            <% options = options_from_collection_for_select(Company.all, 'id', 'name',:selected => @project.company_id) %>
            <%= f.select :company_id,  options, {} ,:class => "form-control" %>
          </div>
        </div>
      <% else %>
        <div class="col-md-6">
          <div class="field">
            <%= label_tag :industry_name %><br>
            <input type="text" readonly="readonly" value="<%= current_user.company.name %>" class="form-control" />
            <input type="hidden" name="project[company_id]" value="<%= current_user.company_id %>" />
          </div>
        </div>
      <% end %>  
        <div class="col-md-6">
          <div class="field">
            <%= label_tag :appointed_person %><br>
            <% options = options_from_collection_for_select(User.where(:role_cd => 1), 'id', 'name', :selected => @project.appointed_person) %>
            <%= f.select :appointed_person,  options, {} ,:class => "form-control" %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="field">
            <%= label_tag :executive %><br>
            <% options = options_from_collection_for_select(User.where(:role_cd => 0), 'id', 'name',:selected => @project.executive) %>
            <%= f.select :executive,  options,  {} ,:class => "form-control" %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="field">
            <%= label_tag :inflation %><br>
            <%= f.text_field :inflation, :class => "form-control" %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="field">
            <%= label_tag :obsolete %><br>
            <%= f.text_field :obsolete, :class => "form-control" %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="field">
            <%= label_tag :upload_excel %><br>
            <%= f.file_field :file, :class => "form-control" , id: "file-field" %>
          </div>
        </div>
      </div>
      <input type="hidden" name="id" value="<%= @project.id %>" />
      <div class="row">
        <div class="col-md-2">
          <div class="actions">
            <%= submit_tag "#{@project.id.present? ? 'Update' : 'Create'}", :class => "upload btn btn-default" %>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <strong>You are not authorized!</strong>  
  <% end %>
  <br>
</div>
<script type="text/javascript">
  $(".preloader").hide();
  $(document).ready(function(){
    $(".upload").click(function(){
      if ($("#file-field").val() != '') {
        $(".preloader").show();
      }
    });
  });
</script>   
<style type="text/css">
  .preloader {
    opacity: 0.6;
  }
</style>

app/views/home/edit_project.html.erb
<div id="page-content">
  <div class="content-header">
    <div class="header-section">
      <h1>
        <i class="fa fa-users"></i>
        Projects
        <br>
        <br>
        <small></small>
      </h1>
    </div>
  </div>
  <ul class="breadcrumb breadcrumb-top">
    <li>Dashboard</li>
    <li><a href="/">Projects</a></li>
  </ul>
	<%= render :partial => "project" %>
</div>	

app/views/home/hr.html.erb
  <div id="page-content">
  <div class="content-header">
    <div class="header-section">
      <h1>
        <i class="fa fa-users"></i>
        HR
        <br>
        <br>
        <small></small>
      </h1>
    </div>
  </div>
  <ul class="breadcrumb breadcrumb-top">
    <li>Dashboard</li>
    <li><a href="/hr">HR</a></li>
  </ul>
  <%= render 'layouts/messages' %>
  <div class="block">
    <div class="block-title">
      <h2>HR</h2>
    </div>
    <%= link_to 'New HR', home_add_hr_path, :class => "btn btn-default" %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Company</th>
          <th>Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= user.company.present? ? user.company.name : "" %></td>
            <td><%= link_to "Edit", home_edit_user_path({:id => user.id}), :class => "btn btn-warning" %>
            <%= link_to "Delete", home_delete_user_path({:id => user.id}), :method => :delete, data: { confirm: 'Are you sure?' } , :class => "btn btn-danger" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/home/index.html.erb
<div id="page-content">
  <div class="content-header">
    <div class="header-section">
      <% if management? %>
        <%= search_form_for @q, url: home_index_path, html: { method: :get } do |f| %>
          <div class="row">
            <% if current_user.role == :admin %>
              <div class="col-md-6">
                <div class="field">
                  <%= label_tag :industry_name %><br>
                  <% options = options_from_collection_for_select(Company.all, 'id', 'name', :selected => params[:q].try(:[],:company_id_eq)) %>
                  <%= f.select :company_id_eq,  options, {} ,:class => "form-control" %>
                </div>
              </div>
            <% else %>
              <div class="col-md-6">
                <div class="field">
                  <%= label_tag :industry_name %><br>
                  <input type="text" readonly="readonly" value="<%= current_user.company.name %>" class="form-control" />
                  <input type="hidden" name="company_id_eq" value="<%= current_user.company_id %>" />
                </div>
              </div>
            <% end %>
            <div class="col-md-6">
              <label>End Date</label>
              <%= f.date_field :end_date_lteq, :class => "form-control" %>
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-md-2">
              <input type="submit" value="Search" class="btn btn-default" />
            </div>
          </div>  
        <% end %>
      <% else %>
        <strong>Dashboard</strong>
      <% end %>  
    </div>
  </div>
  <ul class="breadcrumb breadcrumb-top">
    <li>Dashboard</li>
    <li><a href="/"><%= management? ? "Projects" : "" %></a></li>
  </ul>
  <%= render 'layouts/messages' %>
  <% if management? %>
    <div class="block">
      <div class="block-title">
        <h2>Projects</h2>
      </div>
      <%= link_to "Create new Project", home_new_project_path, :class => "btn btn-default" %>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Bank</th>
            <th>End Date</th>
            <th>Industry Type</th>
            <th>Industry Name</th>
            <th>Appointed Person</th>
            <th>Executive</th>
            <th>Inflation Factor</th>
            <th>Obsolete Factor</th>
            <th>Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @projects.each do |project| %>
            <tr>
              <td><%= project.name %></td>
              <td><%= project.bank_name %></td>
              <td><%= project.end_date %></td>
              <td><%= project.company_type %></td>
              <td><%= project.company.present? ? project.company.name : "" %></td>
              <td><%= username project.appointed_person %></td>
              <td><%= username project.executive %></td>
              <td><%= project.inflation %></td>
              <td><%= project.obsolete %></td>
              <td class="white-space"><%= link_to "<i class='fa fa-eye'></i>".html_safe, home_show_excel_path({:id => project.id}), :class => "btn-xs btn-default" %>
              <%= link_to "<i class='fa fa-pencil'></i>".html_safe, home_edit_project_path({:id => project.id}), :class => "btn-xs btn-warning" %>
              <%= link_to "<i class='fa fa-times'></i>".html_safe, home_delete_project_path({:id => project.id}), :method => :delete, data: { confirm: 'Are you sure?' } , :class => "btn-xs btn-danger" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= will_paginate @projects, renderer: BootstrapPagination::Rails, :class => "pagination" %>
    </div>
  <% else %>

  <% end %>  
</div>
  	

app/views/home/market_value.html.erb
<div id="page-content">
  <div class="content-header">
    <div class="header-section">
    <% if management? %>
      <%= render partial: "market_value" %>
    <% else %>
      <strong>You are not authorized!</strong>  
    <% end %>
    </div>
  </div>
  <ul class="breadcrumb breadcrumb-top">
    <li>Dashboard</li>
    <li><a href="/">Projects</a></li>
  </ul>
  <% if management? %>
    <div class="block">
    <div class="block-title">
      <h2><%= @record.com_name %></h2>
    </div>
      <div class="table-responsive">
      <% if @records.present? %>
      <%= form_tag(home_update_market_value_path, :method => "post") do %>
        <table class="table table-vcenter table-striped">
          <thead>
            <tr>
              <th>Name</th>
              <th>Hs Code</th>
              <th>Description</th>
              <th>Country</th>
              <th>Price/Unit</th>
              <th>Source</th>
              <th>Choose</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <% @records.each do |record| %>
              <tr>
              <td><%=record.name%></td>
              <td><%=record.hs_code%></td>
              <td><%=record.desc%></td>
              <td><%=record.country%></td>
              <td><%=record.price_pp%></td>
              <td><%=record.source%></td>
              <td align="center"><input type="radio" name="value" value="<%=record.id%>" class="form-control"></td>
              <td><%= link_to "<i class='fa fa-times'></i>".html_safe, home_delete_scrap_path({:id => record.id }), :method => :delete, :data => { confirm: "Are you sure?" }, :class => "btn-xs btn-danger" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <input type="hidden" name="record_id" value="<%=@record.id%>" />
        <input type="submit" value="Save" class="btn btn-default" />
        <% end %>
      <% else %>
      <div class="text-center">
        <strong>No records available! </strong><br/>
      </div>
      <% end %>
      </div>
    </div>
  <% else %>
    <strong>you are not authrorized!</strong>
  <% end %>  
</div>

app/views/home/show_excel.html.erb
<div id="page-content">
  <div class="content-header">
    <div class="header-section">
      <% if management? %>
      <strong><h1><%= @excel.present? && @excel.id.present? ? "Update Record" : "Add New Record" %></h1></strong>
      <br>
      <%= render partial: "record" %>
    <% else %>
      <strong>You are not authorized!</strong>  
    <% end %>
    </div>
  </div>
  <ul class="breadcrumb breadcrumb-top">
    <li>Dashboard</li>
    <li><a href="/">Projects</a></li>
  </ul>
  <%= render 'layouts/messages' %>
  <% if management? %>
    <div class="block">
      <div class="block-title">
        <h2><%= @project.name %></h2>
      </div>
      <div class="table-responsive">
      <%= link_to "Download Excel", home_show_excel_path(request.parameters.merge({:format => :xlsx})), :class => "btn btn-default" %>
        <table class="table table-vcenter table-striped">
          <thead>
            <tr>
              <th>Name of Component</th>
              <th>Type</th>
              <th>Purchase Date</th>
              <th>Location</th>
              <th>Industry</th>
              <th>Quantity</th>
              <th>Purchase Price/Unit</th>
              <th>Est Price from Soft Volt A</th>
              <th>Est Price from Past Projects B</th>
              <th>Market Value C</th>
              <th>Expected Life</th>
              <th>Value Used</th>
              <th>Est Date</th>
              <th>Remaining Life</th>
              <th>Import/Export</th>
              <th>Inflation Factor</th>
              <th>Obsolete Factor</th>
              <th>Final Value</th>
              <th>Source</th>
              <th>Action</th>
            </tr>
          </thead>

          <tbody>
            <% @records.each do |record| %>
              <tr>
                <td><%= record.com_name %></td>
                <td><%= record.com_type %></td>
                <td><%= record.purchase_date %></td>
                <td><%= record.location %></td>
                <td><%= record.company_type %></td>
                <td><%= record.quantity %></td>
                <td><%= record.purchase_unit %></td>
                <td><%= record.est_price_soft %></td>
                <td><%= record.est_price_pp %></td>
                <td><%= record.market_value %></td>
                <td><%= record.exp_life %></td>
                <td><%= record.values_used %></td>
                <td><%= record.date_purchase %></td>
                <td><%= record.remain_life %></td>
                <td><%= record.import_export %></td>
                <td><%= record.inflation %></td>
                <td><%= record.obsolete %></td>
                <td><button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal<%=record.id%>"><%= record.final_value %></button></td>
                <td><%= record.source %></td>
                <td style="white-space: nowrap;">
                <%= link_to "Market Value", home_market_value_path({:id => record.id}), :class => "btn btn-default" %>  
                <%= link_to "<i class='fa fa-pencil'></i>".html_safe, home_show_excel_path({:id => @project.id, :record_id => record.id }), :class => "btn-xs btn-warning open-col" %>
                <%= link_to "<i class='fa fa-times'></i>".html_safe, home_delete_record_path({:id => record.id }), :method => :delete, :data => { confirm: "Are you sure?" }, :class => "btn-xs btn-danger" %></td>
              </tr>
              <div id="myModal<%=record.id%>" class="modal fade" role="dialog">
                <div class="modal-dialog">

                  <!-- Modal content-->
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                      <h4 class="modal-title">Final Value</h4>
                    </div>
                    <div class="modal-body">
                      <h2>Select Final Value</h2>
                      <p>
                        <%= form_tag (update_final_value_path) do %>
                          <div class="form-group">
                            <label>Type A Value:</label>
                            <input type="radio" name="value" value="<%= final_value_a(record.id) %>" class="form-control type-a">
                            <%= final_value_a(record.id) %>
                          </div>
                          <div class="form-group">
                            <label>Type B Value:</label>
                            <input type="radio" name="value" value="<%= final_value_b(record.id) %>" class="form-control type-b">
                            <%= final_value_b(record.id) %>
                          </div>
                          <div class="form-group">
                            <label>Type C Value:</label>
                            <input type="radio" name="value" value="<%= final_value_c(record.id) %>" class="form-control type-c">
                            <%= final_value_c(record.id) %>
                          </div>
                          <div class="form-group">
                            <label>Type D Value:</label>
                            <input type="radio" name="value" value="<%= record.est_price_pp.present? ? record.est_price_pp : 0.0 %>" class="form-control type-d">
                            <%= record.est_price_pp.present? ? record.est_price_pp : 0.0 %>
                          </div>
                          <input type="hidden" name="record_id" value="<%=record.id%>" />
                          <div class="form-group">
                            <input type="submit" value="Save" class="btn btn-primary" />
                          </div>
                        <% end %>
                      </p>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                  </div>

                </div>
              </div>
            <% end %>
          </tbody>
        </table>
      </div>
      <%= will_paginate @records, renderer: BootstrapPagination::Rails, :class => "pagination" %>
    </div>
  <% else %>
    <strong>you are not authrorized!</strong>
  <% end %>  
</div>