config/routes.rb
Rails.application.routes.draw do
  resources :companies
  get 'home/index'

  devise_for :users
  root to: "home#index"
  get '/hr' => 'home#hr'
  get '/home/add_hr' => 'home#add_hr'
  get '/home/add_user' => 'home#add_user'
  post '/home/save_user' => 'home#save_user'
  post '/home/update_user' => 'home#update_user'
  delete '/home/delete_user' => 'home#delete_user'
  delete '/home/delete_project' => 'home#delete_project'
  get '/home/edit_user' => 'home#edit_user'
  get '/employees' => 'home#employees'
  get '/home/new_project' => 'home#new_project'
  post '/home/save_project' => 'home#save_project'
  get '/home/edit_project' => 'home#edit_project'
  post '/home/update_project' => 'home#update_project'
  get '/home/show_excel' => 'home#show_excel'
  get '/ongoing_projects' => 'home#ongoing_projects'
  get '/completed_projects' => 'home#completed_projects'
  post '/home/save_record' => 'home#save_record'
  get '/edit_record' => 'home#edit_record'
  delete '/home/delete_record' => 'home#delete_record'
  delete '/home/delete_scrap' => 'home#delete_scrap'
  get '/home/market_value' => 'home#market_value'
  post '/home/update_market_value' => 'home#update_market_value'
  post '/save_market_value' => 'home#save_market_value'
  get 'scrap_data' => 'home#scrap_data'
  post 'save_scrap_data' => 'home#save_scrap_data'
  post 'update_final_value' => 'home#update_final_value'

end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :users, :dependent => :destroy
	has_many :projects, :dependent => :destroy
	validates_presence_of :name
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :check_admin
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to companies_url, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to companies_url, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name)
    end

    def check_admin
      if current_user.role == :admin
        return true
      else
        root_url
      end
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<div id="page-content">
  <div class="content-header">
    <div class="header-section">
      <h1>
        <i class="fa fa-industry"></i>
        Companies
        <br>
        <br>
        <small></small>
      </h1>
    </div>
  </div>
  <ul class="breadcrumb breadcrumb-top">
    <li>Dashboard</li>
    <li><a href="/companies">Companies</a></li>
  </ul>
  <%= render 'layouts/messages' %>
  <div class="block">
    <div class="block-title">
      <h2>Companies</h2>
    </div>
    <%= form_for(@company) do |f| %>
      <% if @company.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

          <ul>
          <% @company.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="row">
        <div class="col-md-6">
          <div class="field">
            <%= f.label :name %><br>
            <%= f.text_field :name, :class => "form-control" %>
          </div>    
        </div>
      </div>
      <div class="actions">
        <%= f.submit class: "btn btn-default" %>
      </div>
    <% end %>
    <br>
  </div>
</div>

app/views/companies/edit.html.erb
<%= render 'form' %>

app/views/companies/index.html.erb
<div id="page-content">
  <div class="content-header">
    <div class="header-section">
      <h1>
        <i class="fa fa-industry"></i>
        Companies
        <br>
        <br>
        <small></small>
      </h1>
    </div>
  </div>
  <ul class="breadcrumb breadcrumb-top">
    <li>Dashboard</li>
    <li><a href="/companies">Companies</a></li>
  </ul>
  <%= render 'layouts/messages' %>
  <div class="block">
    <div class="block-title">
      <h2>Companies</h2>
    </div>
    <%= link_to 'New Company', new_company_path, :class => "btn btn-default" %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @companies.each do |company| %>
          <tr>
            <td><%= company.name %></td>
            <td><%= link_to 'Show', company, :class => "btn btn-default" %>
            <%= link_to 'Edit', edit_company_path(company), :class => "btn btn-warning" %>
            <%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/companies/new.html.erb
<%= render 'form' %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>